// <auto-generated />
using BranchService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BranchService.Migrations
{
    [DbContext(typeof(BranchDbContext))]
    [Migration("20241201171418_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BranchService.Data.Models.Branch.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            BranchLocation = "Sheffield"
                        },
                        new
                        {
                            BranchId = 2,
                            BranchLocation = "Chesterfield"
                        },
                        new
                        {
                            BranchId = 3,
                            BranchLocation = "Manchester"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
