// <auto-generated />
using BranchService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BranchService.Migrations
{
    [DbContext(typeof(BranchDbContext))]
    partial class BranchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BranchService.Data.Models.Branch.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            BranchLocation = "Sheffield"
                        },
                        new
                        {
                            BranchId = 2,
                            BranchLocation = "Chesterfield"
                        },
                        new
                        {
                            BranchId = 3,
                            BranchLocation = "Manchester"
                        },
                        new
                        {
                            BranchId = 4,
                            BranchLocation = "Leeds"
                        },
                        new
                        {
                            BranchId = 5,
                            BranchLocation = "London"
                        });
                });

            modelBuilder.Entity("BranchService.Data.Models.Branch.BranchUserConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchUserConnections");
                });

            modelBuilder.Entity("BranchService.Data.Models.Branch.BranchUserConnection", b =>
                {
                    b.HasOne("BranchService.Data.Models.Branch.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });
#pragma warning restore 612, 618
        }
    }
}
